### ISSUE TITLE
gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye. Trace/breakpoint trap (core dumped)

### ISSUE THREAD

**Issue by SYK-08** [Splode/pomotroid#212] opened 2022-03-17 13:32 UTC
_gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye. Trace/breakpoint trap (core dumped)_
Execution failed and got this error message when tried to execute Pomotroid.

System info-
OS: Manjaro 21.2.4 Qonos
Kernel: x86_64 Linux 5.10.102-1-MANJARO
Shell: bash 5.1.16
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx @ 8x 2.1GHz
GPU: AMD/ATI Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series]
RAM: 5886MiB

**Comment by maxfrei750** [comment] 2022-03-24 10:48
I also encountered this issue. I found the following workaround:
`pomotroid --no-sandbox` (see [here](https://bugzilla.suse.com/show_bug.cgi?id=1191012))

**Comment by maxfrei750** [comment] 2022-03-24 10:48
I just found that this issue is a duplicate of #207.

**Comment by SYK-08** [comment] 2022-04-05 10:09
> I also encountered this issue. I found the following workaround: `pomotroid --no-sandbox` (see [here](https://bugzilla.suse.com/show_bug.cgi?id=1191012))

Thanks buddy :) It worked

**Closed** 2022-04-05 10:10 UTC

**Comment by maxfrei750** [comment] 2022-04-05 10:12
@SYK-08 You're welcome! :-)
